CXX=clang++

LDFLAGS=  -lsfml-system -lsfml-window -lsfml-graphics

CXXFLAGS= -g -Wall -Wextra -std=c++0x


OBJS=Animated.o main.o
NAME=SFMLSandbox


all:$(NAME)

$(NAME):$(OBJS)
	$(CXX) $(OBJS) -o $(NAME) $(LDFLAGS)

clean:
	rm $(NAME) $(OBJS)
